### ISSUE TITLE
AnalyseSensitivity update

### ISSUE THREAD

**Issue by yramachers** [SuperNEMO-DBD/AllAnalyses#6]
After the recent SensitivityModule updates, this script would require an update or refresh. I have adapted all the branch names for reading from sensitivity... to reco... but it still doesn't like it. Maybe a type change too? This is a useful analysis script particularly for my non-programming undergraduate students hence I would prefer not to loose it entirely.

**Comment by cherylepatrick** [comment]
I'll fix it @yramachers - I know what I changed.

**Comment by cherylepatrick** [comment]
Actually @yramachers it's not obvious to me why that wouldn't work - can you tell me the error you got? Do you have all new brio files made with the new sensitivity module? I haven't regenerated them all yet so I can have a go at that, but do you need this in a hurry? I'm going to be underground all next week but if it's urgent I can look at it over the weekend or while I am in France.

**Comment by cherylepatrick** [comment]
Hi @yramachers - I think I fixed this in the branch [NewSensitivityModuleBranchNames](https://github.com/SuperNEMO-DBD/AllAnalyses/tree/NewSensitivityModuleBranchNames) but I only made tiny simulation files to test it on, so the results looked kind of garbage as the backgrounds didn't really pass the cuts. No errors from the branch naming though. Do you think you could try it on your reconstructed files sometime and see if it works? Thanks!

**Comment by yramachers** [comment]
No worries, I reckon I got it working again. Are there plans to upgrade the scripts anyway, i.e. including other figure productions, options or such like, or get more analysis scripts on here? While going through the script, I found it very useful adding to the technical write ups of analyses. I would consider such scripts as good educational material on SNEMO analysis.
Anyway, I think this issue can be closed. No extra stress needed underground.

**Comment by cherylepatrick** [comment]
Yes, I want to make a new version of this in its own repo as a general basic analysis script to use in the MC Challenges etc. When I do that, I'll also update the comments and tidy up the script so it serves better as a template for new people (I've already done a bit of tidying and updating the docs for the SensitivityModule and this is next on the list). As other people are going to use it, I'll also take out the tacky stuff like my hardcoded paths etc and make it generally more configurable. Feel free to send requests!
